### ISSUE TITLE
this program is very useful

### ISSUE THREAD

**Issue by ifdog** [IOsetting/stc8prog#1]
如题。十分感谢。

**Comment by ifdog** [comment]
however the new 1.2 release package "stc8prog_1.2_amd64.tar.gz" seems to be 1.1 from "--version"? and 1.1 release was 1.0? is this right?

**Comment by IOsetting** [comment]
Apologies, I didn't update the version number in code. 

This has been fixed.

**Comment by IOsetting** [comment]
Close this for the issue had been resolved.
