### ISSUE TITLE
是否支持自动REST

### ISSUE THREAD

**Issue by 0x76long** [IOsetting/stc8prog#5]
先通过串口发送一些自定义数据，然后mcu自动REST和 stcgal 的 -r 功能一样尼

**Comment by IOsetting** [comment]
这个功能是需要mcu主动监控串口或者在中间使用一片单独的mcu监控串口实现的吧? 
main分支有一个`-r`参数可以将DTR置为无效, 可以用这个参数触发reset

**Comment by IOsetting** [comment]
版本1.3已经增加烧录前拉低RTS的功能, 支持自动下载. 在Linux下可以直接接DTR实现自动下载.
